#!/bin/bash

file=`cat $1`
regex="^(chore|feat|fix|docs|style|refactor|test|revert)(\\(([a-z0-9\\-]+)\\))?: (.+)";

if ! [[ $file =~ $regex ]]; then
	echo "Invalid commit message. Format must match: ^(chore|feat|fix|docs|style|refactor|test|revert)(\\(([a-z0-9]+)\\))?: (.+)"
	exit 1
fi
